spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: shangxu929
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.136.128
    port: 6379
    password: shangxu929
server:
  port: 8888